markdown:       kramdown
kramdown:
  auto_ids:     true
encoding:       UTF-8
exclude:
  - .git/
  - package.json
  - package-lock.json
  - node_modules
sass:
  sass_dir: ./
  style: compressed

theme: jekyll-theme-primer

plugins:
  - jekyll-seo-tag

title: "👋 Hello, Microsoft"
description: "@nazimboudeffa"

twitter:
  username: nazimboudeffa

author:
  name: Nazim Boudeffa
  twitter: nazimboudeffa
